apiVersion: apps/v1
kind: Deployment

metadata:
  name: booking-system
  namespace: booking-system

spec:
  replicas: 1

  selector:
    matchLabels:
      app: booking-system

  template:
    metadata:
      labels:
        app: booking-system

    spec:
      containers:
        - name: booking-system
          image: booking-system:1.0
          imagePullPolicy: Never

          ports:
            - containerPort: 8080

          env:
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: booking-system-config
                  key: DB_URL

            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: booking-system-secret
                  key: DB_USERNAME

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: booking-system-secret
                  key: DB_PASSWORD

            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: booking-system-config
                  key: SPRING_PROFILES_ACTIVE

          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 40
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3

          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"

            limits:
              cpu: "500m"
              memory: "1Gi"