apiVersion: v1
kind: ConfigMap
metadata:
  name: booking-system-config
  namespace: booking-system

data:
  DB_URL: jdbc:postgresql://host.docker.internal:5432/postgres
  SPRING_PROFILES_ACTIVE: default